variable "resource_group_name"  {}
variable "resource_group_location"  {}
variable "tags" {}
variable "vnet_name" {}
variable "vnet_address_prefix"  {}
variable "subnet_names"  {}
variable "subnet_address_prefix"  {}
variable "service_endpoints"  {}
variable "storage_name" {}
variable "account_kind" {}
variable "account_tier" {}
variable "access_tier" {}
variable "account_replication_type" {}